---
title: "LabSession1"
author: "Keith Teo"
date: "2023-08-28"
output: html_document
---
```{r load-libraries, echo=TRUE, message=FALSE, warning=FALSE}
# load required packages
library("tidyverse")
library("openxlsx")
library("rpivotTable")
library("dplyr")
library("ggplot2")
library("knitr")
library("psych")
library("kableExtra")
library("RColorBrewer")
library("wooldridge")
```

## R Markdown
```{r Part1 1), Exploring ToothGrowth Dataset}
ToothGrowth

data = ToothGrowth

?ToothGrowth



ToothGrowth

summary(data)

str(data)

ToothGrowth

head(ToothGrowth)

tail(ToothGrowth)


#What is the difference between str() and summary()
```
```{r Part1 2), dplyr Package examples}

dfTooth = ToothGrowth


dfTooth$supp
#2i) Extracting the column supp

dfTooth$supp 

dfTooth %>% select(supp)

#2ii) Extract rows where supp is equal to “VC” and dose is less than 1 and assign the output to df2

df2 = dfTooth %>% filter(supp == "VC" & dfTooth$dose < 1)
df2

#2iii) Extract the values of len where supp is equal to “VC”

dfTooth %>% filter(supp == "VC") %>% select(len)

#2iv) Try to perform the above operations (i, ii, iii) again but this time, assign the output
#to df2.1, df2.2 and df2.3 respectively.

test = dfTooth$len[dfTooth$supp == "VC"]
test

df2.1 = dfTooth %>% select(supp)

df2.2 = dfTooth %>% filter(supp == "VC" & dfTooth$dose < 1)
df2.2

df2.3 = dfTooth %>% filter(supp == "VC") %>% select(len)
df2.3
test

#2v) Use the class function to check the class attribute for each of the ouputs. Use
#is.data.frame function to check whether the output is a dataframe or a vector.
class(df2.1)
class(df2.2)
class(df2.3)
```
```{r Part1 3), dplyr Package manipulate}
#3i )Change the variable name from len to length and assign the output to df3.1
df3.1 = dfTooth %>% rename(length = len)

#3ii) Increase the value of len by 0.5 if supp is equal to OJ and assign the output to
df3.2 = dfTooth %>% mutate(len = case_when(supp == "OJ" ~ len + 0.5, TRUE ~ len))
df3.2.1 = dfTooth %>% mutate(len = ifelse(supp == "OJ", len + 0.5, len ))




#df3.2
#df3.2.1

#3iii) Remove the column dose from the data and assign the output to df3.3
df3.3 = dfTooth %>% select(-dose)

#3iv) Increase the value of dose by 0.1 for all records and rename dose to dose.new and
#assign output to df3.4

df3.4 = dfTooth %>% mutate(dose = dose + 0.1) %>% rename(dose.new = dose)

df3.4


#3v) Create a new variable high.dose and assign it a value of “TRUE” if dose is more than 1
#and “FALSE” if dose is less than or equal to 1. Assign the dataframe with the new variable
#high.dose to df3.5. Export df3.5 to a csv file. Discuss what is the r code to export as an
#excel file (.xlsx).

df3.5 = dfTooth %>% mutate(high.dose = ifelse(dose > 1, "TRUE", "FALSE"))


df3.6 = dfTooth %>% mutate(high.dose = case_when(dose > 1 ~ "TRUE", TRUE ~ "FALSE"))

write.csv(df3.5, "df3.5.csv")



#df3.6
#df3.5
```
```{r Part1 4), Sorting}
# 4i) There are two functions in Base R “sort” and “order” to perform sorting. How do
#these two functions differ? Try to do a sort with each function on
#ToothGrowth$len.

sort(dfTooth$len)

dfTooth$len
order(dfTooth$len)

#4ii) Using a base R function (e.g. order), how can you sort the dataframe ToothGrowth
#in decreasing order of len?

dfTooth[order(dfTooth$len , decreasing = TRUE),]

#4iii) What dplyr function can you use to sort ToothGrowth in increasing order of len?
#Can you also sort the dataframe in decreasing order of len?

dfTooth %>% arrange(len) %>% select(len) # sorts column in ascending order
dfTooth %>% arrange(desc(len)) %>% select(len)  # sorts column in descending order

```

```{r Part1 5), factors}
# 5i) Check if supp is a factor vector. First type ToothGrowth$supp. What do you
# observe with the output?

dfTooth$supp

#5ii) Next use is.factor() and is.ordered() to check if supp is a factor and is so
#whether it is an ordered factor.

#https://r4ds.had.co.nz/factors.html#:~:text=In%20R%2C%20factors%20are%20used,to%20work%20with%20than%20characters.

is.factor(dfTooth$supp)
is.ordered(dfTooth$supp)

#5iii) Now supposed we find that vitamin C (VC) is a superior supplement compared to
#orange juice (OJ), and we want to order supp such that VC is a higher level than OJ, how
#could we do this? (Hint:Assign factor_supp toToothGrowth$supp)

factor_supp = factor(dfTooth$supp, levels = c("OJ","VC") , ordered= TRUE)
factor_supp

is.factor(factor_supp)
is.ordered(factor_supp)


factor_supp_dplyr <- ToothGrowth %>% mutate(supp = factor(supp, levels = c("OJ","VC") , ordered= TRUE))
factor_supp_dplyr$supp



is.factor(factor_supp_dplyr$supp)
is.ordered(factor_supp_dplyr$supp)

```
